# Generated by Django 5.0 on 2023-12-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('color', models.CharField(default='#a74d47', max_length=10)),
                ('is_online', models.BooleanField(null=True)),
                ('address', models.CharField(default='', max_length=60)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
