# Generated by Django 5.0 on 2023-12-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_alter_card_address_alter_card_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='address',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
